apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: default
  labels:
    app: site
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
        - name: app
          image: ikonera/cicd-project
          ports:
            - containerPort: 3000
      nodeSelector:
        app: site

# A copier dans Jenkins
